# Generated by Django 5.0.4 on 2024-04-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AviaTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('city1', models.CharField(max_length=100)),
                ('city2', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('date_of_arrival', models.DateField()),
                ('date_of_departure', models.DateField()),
                ('duration_of_visit', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Avia tour',
                'verbose_name_plural': 'Avia tours',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=12)),
                ('num_of_people', models.IntegerField()),
                ('acceptance', models.BooleanField(default=False)),
                ('total_cost', models.BooleanField()),
                ('aviatour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.aviatour')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
