# Generated by Django 5.0.4 on 2024-04-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('cost_per_person', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.hotel'),
            preserve_default=False,
        ),
    ]
